# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/preferences.ui'
#
# Created: Tue Dec 25 12:28:19 2012
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogPreferences(object):
    def setupUi(self, DialogPreferences):
        DialogPreferences.setObjectName(_fromUtf8("DialogPreferences"))
        DialogPreferences.resize(600, 300)
        self.verticalLayout = QtGui.QVBoxLayout(DialogPreferences)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(DialogPreferences)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName(_fromUtf8("tabGeneral"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabGeneral)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkGeneralRecentLoad = QtGui.QCheckBox(self.tabGeneral)
        self.checkGeneralRecentLoad.setObjectName(_fromUtf8("checkGeneralRecentLoad"))
        self.verticalLayout_4.addWidget(self.checkGeneralRecentLoad)
        self.checkGeneralReadingsStrip = QtGui.QCheckBox(self.tabGeneral)
        self.checkGeneralReadingsStrip.setObjectName(_fromUtf8("checkGeneralReadingsStrip"))
        self.verticalLayout_4.addWidget(self.checkGeneralReadingsStrip)
        self.checkGeneralFindUpdates = QtGui.QCheckBox(self.tabGeneral)
        self.checkGeneralFindUpdates.setObjectName(_fromUtf8("checkGeneralFindUpdates"))
        self.verticalLayout_4.addWidget(self.checkGeneralFindUpdates)
        spacerItem = QtGui.QSpacerItem(20, 139, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tabGeneral, _fromUtf8(""))
        self.tabAppearance = QtGui.QWidget()
        self.tabAppearance.setObjectName(_fromUtf8("tabAppearance"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabAppearance)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboContentFontFamily = QtGui.QFontComboBox(self.tabAppearance)
        self.comboContentFontFamily.setObjectName(_fromUtf8("comboContentFontFamily"))
        self.horizontalLayout.addWidget(self.comboContentFontFamily)
        self.spinContentFontSize = QtGui.QSpinBox(self.tabAppearance)
        self.spinContentFontSize.setMinimum(1)
        self.spinContentFontSize.setMaximum(72)
        self.spinContentFontSize.setProperty("value", 12)
        self.spinContentFontSize.setObjectName(_fromUtf8("spinContentFontSize"))
        self.horizontalLayout.addWidget(self.spinContentFontSize)
        self.buttonContentColorFg = QtGui.QPushButton(self.tabAppearance)
        self.buttonContentColorFg.setObjectName(_fromUtf8("buttonContentColorFg"))
        self.horizontalLayout.addWidget(self.buttonContentColorFg)
        self.buttonContentColorBg = QtGui.QPushButton(self.tabAppearance)
        self.buttonContentColorBg.setObjectName(_fromUtf8("buttonContentColorBg"))
        self.horizontalLayout.addWidget(self.buttonContentColorBg)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.textContentSample = QtGui.QPlainTextEdit(self.tabAppearance)
        self.textContentSample.setObjectName(_fromUtf8("textContentSample"))
        self.verticalLayout_3.addWidget(self.textContentSample)
        self.tabWidget.addTab(self.tabAppearance, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabSearch)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.tabSearch)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.spinSearchScanMax = QtGui.QSpinBox(self.tabSearch)
        self.spinSearchScanMax.setMinimum(1)
        self.spinSearchScanMax.setObjectName(_fromUtf8("spinSearchScanMax"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinSearchScanMax)
        self.label_6 = QtGui.QLabel(self.tabSearch)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.spinSearchResultMax = QtGui.QSpinBox(self.tabSearch)
        self.spinSearchResultMax.setMinimum(1)
        self.spinSearchResultMax.setObjectName(_fromUtf8("spinSearchResultMax"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinSearchResultMax)
        self.checkSearchGroupByExp = QtGui.QCheckBox(self.tabSearch)
        self.checkSearchGroupByExp.setObjectName(_fromUtf8("checkSearchGroupByExp"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.checkSearchGroupByExp)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem1 = QtGui.QSpacerItem(423, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.tabAnki = QtGui.QWidget()
        self.tabAnki.setObjectName(_fromUtf8("tabAnki"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabAnki)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_13 = QtGui.QLabel(self.tabAnki)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.comboBoxAnkiDeck = QtGui.QComboBox(self.tabAnki)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxAnkiDeck.sizePolicy().hasHeightForWidth())
        self.comboBoxAnkiDeck.setSizePolicy(sizePolicy)
        self.comboBoxAnkiDeck.setObjectName(_fromUtf8("comboBoxAnkiDeck"))
        self.horizontalLayout_4.addWidget(self.comboBoxAnkiDeck)
        self.label_12 = QtGui.QLabel(self.tabAnki)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.comboBoxAnkiModel = QtGui.QComboBox(self.tabAnki)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxAnkiModel.sizePolicy().hasHeightForWidth())
        self.comboBoxAnkiModel.setSizePolicy(sizePolicy)
        self.comboBoxAnkiModel.setObjectName(_fromUtf8("comboBoxAnkiModel"))
        self.horizontalLayout_4.addWidget(self.comboBoxAnkiModel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.label_11 = QtGui.QLabel(self.tabAnki)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_5.addWidget(self.label_11)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tableAnkiFields = QtGui.QTableWidget(self.tabAnki)
        self.tableAnkiFields.setObjectName(_fromUtf8("tableAnkiFields"))
        self.tableAnkiFields.setColumnCount(2)
        self.tableAnkiFields.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableAnkiFields.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableAnkiFields.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_3.addWidget(self.tableAnkiFields)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.tabAnki)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabAnki)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tabAnki)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tabAnki)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabAnki)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tabAnki)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tabAnki)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.tabAnki)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tabAnki, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(DialogPreferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogPreferences)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogPreferences.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogPreferences.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogPreferences)

    def retranslateUi(self, DialogPreferences):
        DialogPreferences.setWindowTitle(_translate("DialogPreferences", "Preferences", None))
        self.checkGeneralRecentLoad.setText(_translate("DialogPreferences", "Load recent file on startup", None))
        self.checkGeneralReadingsStrip.setText(_translate("DialogPreferences", "Strip readings in from loaded files", None))
        self.checkGeneralFindUpdates.setText(_translate("DialogPreferences", "Check for updates on startup", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("DialogPreferences", "General", None))
        self.buttonContentColorFg.setText(_translate("DialogPreferences", "Foreground...", None))
        self.buttonContentColorBg.setText(_translate("DialogPreferences", "Background...", None))
        self.textContentSample.setPlainText(_translate("DialogPreferences", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam accumsan nisi a leo faucibus ut varius velit fringilla. Cras hendrerit eleifend porttitor. Quisque eu elit quis tellus hendrerit ornare et ac tellus. Nunc id felis ut sapien blandit viverra vel ac est. Ut erat lorem, rutrum at scelerisque sollicitudin, lacinia quis diam. Suspendisse potenti. Integer id justo ac ligula aliquet mattis. Etiam malesuada faucibus risus, vel hendrerit elit consectetur quis. Etiam consectetur ipsum ut odio feugiat suscipit. Etiam a tellus metus. ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAppearance), _translate("DialogPreferences", "Appearance", None))
        self.label_5.setText(_translate("DialogPreferences", "Maximum scan length", None))
        self.label_6.setText(_translate("DialogPreferences", "Maximum result count", None))
        self.checkSearchGroupByExp.setText(_translate("DialogPreferences", "Group results by expression", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("DialogPreferences", "Search", None))
        self.label_13.setText(_translate("DialogPreferences", "Deck", None))
        self.label_12.setText(_translate("DialogPreferences", "Model", None))
        self.label_11.setText(_translate("DialogPreferences", "Specify how your model fields are populated when adding facts", None))
        item = self.tableAnkiFields.horizontalHeaderItem(0)
        item.setText(_translate("DialogPreferences", "Field", None))
        item = self.tableAnkiFields.horizontalHeaderItem(1)
        item.setText(_translate("DialogPreferences", "Value", None))
        self.label_7.setText(_translate("DialogPreferences", "%e", None))
        self.label_2.setText(_translate("DialogPreferences", "Reading", None))
        self.label_3.setText(_translate("DialogPreferences", "Glossary", None))
        self.label_9.setText(_translate("DialogPreferences", "%g", None))
        self.label_4.setText(_translate("DialogPreferences", "Sentence", None))
        self.label_10.setText(_translate("DialogPreferences", "%s", None))
        self.label_8.setText(_translate("DialogPreferences", "%r", None))
        self.label.setText(_translate("DialogPreferences", "Expression", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnki), _translate("DialogPreferences", "Anki", None))

