# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dev/preferences.ui'
#
# Created: Sat Feb 19 20:53:26 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogPreferences(object):
    def setupUi(self, DialogPreferences):
        DialogPreferences.setObjectName(_fromUtf8("DialogPreferences"))
        DialogPreferences.resize(600, 300)
        self.verticalLayout = QtGui.QVBoxLayout(DialogPreferences)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(DialogPreferences)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName(_fromUtf8("tabGeneral"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabGeneral)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkGeneralRecentLoad = QtGui.QCheckBox(self.tabGeneral)
        self.checkGeneralRecentLoad.setObjectName(_fromUtf8("checkGeneralRecentLoad"))
        self.verticalLayout_4.addWidget(self.checkGeneralRecentLoad)
        self.checkGeneralReadingsStrip = QtGui.QCheckBox(self.tabGeneral)
        self.checkGeneralReadingsStrip.setObjectName(_fromUtf8("checkGeneralReadingsStrip"))
        self.verticalLayout_4.addWidget(self.checkGeneralReadingsStrip)
        self.checkGeneralFindUpdates = QtGui.QCheckBox(self.tabGeneral)
        self.checkGeneralFindUpdates.setObjectName(_fromUtf8("checkGeneralFindUpdates"))
        self.verticalLayout_4.addWidget(self.checkGeneralFindUpdates)
        spacerItem = QtGui.QSpacerItem(20, 139, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tabGeneral, _fromUtf8(""))
        self.tabAppearance = QtGui.QWidget()
        self.tabAppearance.setObjectName(_fromUtf8("tabAppearance"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabAppearance)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboContentFontFamily = QtGui.QFontComboBox(self.tabAppearance)
        self.comboContentFontFamily.setObjectName(_fromUtf8("comboContentFontFamily"))
        self.horizontalLayout.addWidget(self.comboContentFontFamily)
        self.spinContentFontSize = QtGui.QSpinBox(self.tabAppearance)
        self.spinContentFontSize.setMinimum(1)
        self.spinContentFontSize.setMaximum(72)
        self.spinContentFontSize.setProperty(_fromUtf8("value"), 12)
        self.spinContentFontSize.setObjectName(_fromUtf8("spinContentFontSize"))
        self.horizontalLayout.addWidget(self.spinContentFontSize)
        self.buttonContentColorFg = QtGui.QPushButton(self.tabAppearance)
        self.buttonContentColorFg.setObjectName(_fromUtf8("buttonContentColorFg"))
        self.horizontalLayout.addWidget(self.buttonContentColorFg)
        self.buttonContentColorBg = QtGui.QPushButton(self.tabAppearance)
        self.buttonContentColorBg.setObjectName(_fromUtf8("buttonContentColorBg"))
        self.horizontalLayout.addWidget(self.buttonContentColorBg)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.textContentSample = QtGui.QPlainTextEdit(self.tabAppearance)
        self.textContentSample.setObjectName(_fromUtf8("textContentSample"))
        self.verticalLayout_3.addWidget(self.textContentSample)
        self.tabWidget.addTab(self.tabAppearance, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabSearch)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.tabSearch)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.spinSearchScanMax = QtGui.QSpinBox(self.tabSearch)
        self.spinSearchScanMax.setMinimum(1)
        self.spinSearchScanMax.setObjectName(_fromUtf8("spinSearchScanMax"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinSearchScanMax)
        self.label_6 = QtGui.QLabel(self.tabSearch)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.spinSearchResultMax = QtGui.QSpinBox(self.tabSearch)
        self.spinSearchResultMax.setMinimum(1)
        self.spinSearchResultMax.setObjectName(_fromUtf8("spinSearchResultMax"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinSearchResultMax)
        self.checkSearchGroupByExp = QtGui.QCheckBox(self.tabSearch)
        self.checkSearchGroupByExp.setObjectName(_fromUtf8("checkSearchGroupByExp"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.checkSearchGroupByExp)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem1 = QtGui.QSpacerItem(423, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.tabAnki = QtGui.QWidget()
        self.tabAnki.setObjectName(_fromUtf8("tabAnki"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabAnki)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_11 = QtGui.QLabel(self.tabAnki)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_5.addWidget(self.label_11)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tableAnkiFields = QtGui.QTableWidget(self.tabAnki)
        self.tableAnkiFields.setObjectName(_fromUtf8("tableAnkiFields"))
        self.tableAnkiFields.setColumnCount(4)
        self.tableAnkiFields.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableAnkiFields.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableAnkiFields.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableAnkiFields.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableAnkiFields.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_3.addWidget(self.tableAnkiFields)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.tabAnki)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabAnki)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tabAnki)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tabAnki)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabAnki)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tabAnki)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tabAnki)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.tabAnki)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.checkAnkiShowIcon = QtGui.QCheckBox(self.tabAnki)
        self.checkAnkiShowIcon.setObjectName(_fromUtf8("checkAnkiShowIcon"))
        self.verticalLayout_5.addWidget(self.checkAnkiShowIcon)
        self.tabWidget.addTab(self.tabAnki, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(DialogPreferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogPreferences)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogPreferences.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogPreferences.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogPreferences)

    def retranslateUi(self, DialogPreferences):
        DialogPreferences.setWindowTitle(QtGui.QApplication.translate("DialogPreferences", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.checkGeneralRecentLoad.setText(QtGui.QApplication.translate("DialogPreferences", "Load recent file on startup", None, QtGui.QApplication.UnicodeUTF8))
        self.checkGeneralReadingsStrip.setText(QtGui.QApplication.translate("DialogPreferences", "Strip readings in from loaded files", None, QtGui.QApplication.UnicodeUTF8))
        self.checkGeneralFindUpdates.setText(QtGui.QApplication.translate("DialogPreferences", "Check for updates on startup", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), QtGui.QApplication.translate("DialogPreferences", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonContentColorFg.setText(QtGui.QApplication.translate("DialogPreferences", "Foreground...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonContentColorBg.setText(QtGui.QApplication.translate("DialogPreferences", "Background...", None, QtGui.QApplication.UnicodeUTF8))
        self.textContentSample.setPlainText(QtGui.QApplication.translate("DialogPreferences", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam accumsan nisi a leo faucibus ut varius velit fringilla. Cras hendrerit eleifend porttitor. Quisque eu elit quis tellus hendrerit ornare et ac tellus. Nunc id felis ut sapien blandit viverra vel ac est. Ut erat lorem, rutrum at scelerisque sollicitudin, lacinia quis diam. Suspendisse potenti. Integer id justo ac ligula aliquet mattis. Etiam malesuada faucibus risus, vel hendrerit elit consectetur quis. Etiam consectetur ipsum ut odio feugiat suscipit. Etiam a tellus metus. ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAppearance), QtGui.QApplication.translate("DialogPreferences", "Appearance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogPreferences", "Maximum scan length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogPreferences", "Maximum result count", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSearchGroupByExp.setText(QtGui.QApplication.translate("DialogPreferences", "Group results by expression", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), QtGui.QApplication.translate("DialogPreferences", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DialogPreferences", "Specify how your deck\'s model fields are populated when adding facts", None, QtGui.QApplication.UnicodeUTF8))
        self.tableAnkiFields.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogPreferences", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.tableAnkiFields.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogPreferences", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tableAnkiFields.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogPreferences", "Required", None, QtGui.QApplication.UnicodeUTF8))
        self.tableAnkiFields.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("DialogPreferences", "Unique", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogPreferences", "%e", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogPreferences", "Reading", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogPreferences", "Glossary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogPreferences", "%g", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogPreferences", "Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DialogPreferences", "%s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogPreferences", "%r", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogPreferences", "Expression", None, QtGui.QApplication.UnicodeUTF8))
        self.checkAnkiShowIcon.setText(QtGui.QApplication.translate("DialogPreferences", "Show icon in toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnki), QtGui.QApplication.translate("DialogPreferences", "Anki", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
